# Generated by Django 6.0 on 2026-04-12 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cad_cliente', '0007_alter_cliente_options_alter_cliente_managers_and_more'),
        ('filial', '0002_filial_paises'),
        ('motorista', '0003_alter_motorista_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_vonzu', models.BigIntegerField()),
                ('pedido', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('ENTREGA', 'Entrega'), ('RECOLHA', 'Recolha')], max_length=10)),
                ('criado', models.DateTimeField()),
                ('atualizacao', models.DateTimeField()),
                ('prev_entrega', models.DateField(blank=True, null=True)),
                ('dt_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('created', 'Criado'), ('assigned', 'Atribuído'), ('pending', 'Em distribuição'), ('completed', 'Concluído'), ('EA', 'Entrada em armazém e está OK'), ('CA', 'Cliente ausente'), ('R', 'Entrega recusada'), ('DA', 'Difícil acesso (rua)'), ('EM', 'Erro de morada'), ('DVP', 'Entrega com danos visíveis'), ('DVR', 'Entrada em armazém: danos visíveis'), ('cancelled', 'Cancelado'), ('A', 'Pedido Cancelado'), ('CI', 'Entrega com artigos em falta'), ('AO', 'Incumprimento do dia de entrega'), ('PNR', 'Pedido não rececionado'), ('RCD', 'Recolha com danos visíveis (casa cliente)'), ('PIT', 'Pedido incompleto: responsabilidade da transportadora'), ('reschedule_client', 'Reagendamento Responsabilidade Cliente'), ('reschedule_logisticOperator', 'Reagendamento Responsabilidade Transportador'), ('orders_vonzu', 'Entrada em Vonzu'), ('(orders_vonzu)', 'CONTACTO CONFIRMADO'), ('(orders_vonzu))', 'PENDENTE CONTACTO'), ('ExtraviadoOperador', 'Extraviado no Operador'), ('danos_visiveis_embalagem', 'Receção Transportadora: danos visíveis (embalagem)'), ('3799', 'Reagendado Zona Sem entregas dia Planeado'), ('recusa_parcial', 'Recusa parcial (artigos danificados)'), ('conferencia_condicionada', 'Conferência condicionada'), ('reactivar', 'Reactivar (Reagendamento responsabilidade Leroy Merlin)'), ('Reagendamento_Leroy_Merlin', 'Reagendamento responsabilidade Leroy Merlin'), ('returned_to_sender', 'Devolvido ao Cliente'), ('UNKNOWN', 'Estado desconhecido')], max_length=50, null=True)),
                ('volume', models.SmallIntegerField(blank=True, null=True)),
                ('nome_dest', models.CharField(blank=True, max_length=150, null=True)),
                ('email_dest', models.CharField(blank=True, max_length=150, null=True)),
                ('fone_dest', models.CharField(blank=True, max_length=30, null=True)),
                ('fone_dest2', models.CharField(blank=True, max_length=30, null=True)),
                ('endereco_dest', models.CharField(blank=True, max_length=300, null=True)),
                ('codpost_dest', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade_dest', models.CharField(blank=True, max_length=100, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='cad_cliente.cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('filial', models.ForeignKey(db_column='filial_id', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='filial.filial')),
                ('motorista', models.ForeignKey(blank=True, db_column='motorista_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='motorista.motorista')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='TentativaEntrega',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_tentativa', models.DateField()),
                ('estado', models.CharField(blank=True, choices=[('created', 'Criado'), ('assigned', 'Atribuído'), ('pending', 'Em distribuição'), ('completed', 'Concluído'), ('EA', 'Entrada em armazém e está OK'), ('CA', 'Cliente ausente'), ('R', 'Entrega recusada'), ('DA', 'Difícil acesso (rua)'), ('EM', 'Erro de morada'), ('DVP', 'Entrega com danos visíveis'), ('DVR', 'Entrada em armazém: danos visíveis'), ('cancelled', 'Cancelado'), ('A', 'Pedido Cancelado'), ('CI', 'Entrega com artigos em falta'), ('AO', 'Incumprimento do dia de entrega'), ('PNR', 'Pedido não rececionado'), ('RCD', 'Recolha com danos visíveis (casa cliente)'), ('PIT', 'Pedido incompleto: responsabilidade da transportadora'), ('reschedule_client', 'Reagendamento Responsabilidade Cliente'), ('reschedule_logisticOperator', 'Reagendamento Responsabilidade Transportador'), ('orders_vonzu', 'Entrada em Vonzu'), ('(orders_vonzu)', 'CONTACTO CONFIRMADO'), ('(orders_vonzu))', 'PENDENTE CONTACTO'), ('ExtraviadoOperador', 'Extraviado no Operador'), ('danos_visiveis_embalagem', 'Receção Transportadora: danos visíveis (embalagem)'), ('3799', 'Reagendado Zona Sem entregas dia Planeado'), ('recusa_parcial', 'Recusa parcial (artigos danificados)'), ('conferencia_condicionada', 'Conferência condicionada'), ('reactivar', 'Reactivar (Reagendamento responsabilidade Leroy Merlin)'), ('Reagendamento_Leroy_Merlin', 'Reagendamento responsabilidade Leroy Merlin'), ('returned_to_sender', 'Devolvido ao Cliente'), ('UNKNOWN', 'Estado desconhecido')], max_length=50, null=True)),
                ('faturado', models.BooleanField(default=False)),
                ('interno', models.BooleanField(default=False)),
                ('dt_entrega', models.DateField(blank=True, null=True)),
                ('pedido', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'tentativa_entrega',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['filial', 'id_vonzu'], name='pedido_filial__3fe481_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['prev_entrega'], name='pedido_prev_en_838411_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='pedido_estado_01ae34_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('filial', 'id_vonzu'), name='unique_pedido_filial_vonzu'),
        ),
        migrations.AddIndex(
            model_name='tentativaentrega',
            index=models.Index(fields=['pedido', 'data_tentativa'], name='tentativa_e_pedido__2600bf_idx'),
        ),
        migrations.AddIndex(
            model_name='tentativaentrega',
            index=models.Index(fields=['data_tentativa', 'faturado'], name='tentativa_e_data_te_d3c765_idx'),
        ),
    ]
