# Generated by Django 6.0 on 2026-04-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_expresso_tentativa_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='obs_rota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='volume_conf',
            field=models.SmallIntegerField(default=0),
        ),
    ]
