# Generated by Django 6.0 on 2026-04-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_obs_rota_pedido_volume_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativaentrega',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
