# Generated by Django 6.0 on 2026-04-16 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_add_updated_at_tentativaentrega'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tentativaentrega',
            options={'permissions': [('change_carro_tentativaentrega', 'Pode alterar o campo Carro na conferência de volumes')]},
        ),
    ]
