# Generated by Django 6.0 on 2026-04-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_add_lat_lng_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('palete', models.SmallIntegerField(blank=True, null=True)),
                ('volume', models.SmallIntegerField(blank=True, null=True)),
                ('motivo', models.CharField(choices=[('Pedido Cancelado p/ Cliente', 'Pedido Cancelado p/ Cliente'), ('Entrega Recusada', 'Entrega Recusada'), ('Artigos Danificados', 'Artigos Danificados'), ('Cliente Ausente', 'Cliente Ausente'), ('Tipologia de Entrega Errada (Passeio/Domicilio/Grua)', 'Tipologia de Entrega Errada (Passeio/Domicilio/Grua)'), ('Morada Errada', 'Morada Errada'), ('Pedido Adiado', 'Pedido Adiado'), ('Artigos Errados', 'Artigos Errados'), ('Transportadora Errada', 'Transportadora Errada'), ('Outros', 'Outros'), ('Pedido cancelado', 'Pedido cancelado')], max_length=100)),
                ('obs', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'devolucao',
                'indexes': [models.Index(fields=['pedido'], name='devolucao_pedido__80e401_idx'), models.Index(fields=['data'], name='devolucao_data_8723f1_idx')],
            },
        ),
    ]
