# Generated by Django 6.0 on 2026-04-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_add_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativaentrega',
            name='sms_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
