# Generated by Django 6.0 on 2026-04-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_tentativaentrega_sms_enviado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tentativaentrega',
            options={'permissions': [('change_carro_tentativaentrega', 'Pode alterar o campo Carro na conferência de volumes'), ('send_sms_tentativaentrega', 'Pode enviar SMS de notificação de entrega')]},
        ),
    ]
