# Generated by Django 6.0 on 2026-04-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_devolucao_fotos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucao',
            options={'permissions': [('view_relatorio_devolucao', 'Pode acessar o Relatório de Devoluções')]},
        ),
    ]
