# Generated by Django 6.0 on 2026-04-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_add_view_relatorio_devolucao_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='driver',
            field=models.BooleanField(default=False),
        ),
    ]
