# Generated by Django 6.0 on 2026-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_add_driver_and_gsheets_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='geocoding_display',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='geocoding_precision',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
