# Generated by Django 6.0 on 2026-04-27 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorista', '0003_alter_motorista_managers_and_more'),
        ('pedidos', '0015_add_geocoding_fields_to_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('origem', models.CharField(choices=[('Cliente', 'Cliente'), ('Filial', 'Filial')], max_length=10)),
                ('tipo', models.CharField(choices=[('Acondicionamento/Embalagem', 'Acondicionamento/Embalagem'), ('Peso/Volume', 'Peso/Volume'), ('Data/Horário', 'Data/Horário'), ('Outros', 'Outros'), ('Artigo Danificado', 'Artigo Danificado'), ('Artigo Extraviado', 'Artigo Extraviado')], max_length=50)),
                ('artigo', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('fotos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motorista', models.ForeignKey(blank=True, db_column='motorista_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='motorista.motorista')),
                ('pedido', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'incidencia',
                'indexes': [models.Index(fields=['pedido'], name='incidencia_pedido__8a7d2b_idx'), models.Index(fields=['data'], name='incidencia_data_555db9_idx'), models.Index(fields=['origem'], name='incidencia_origem_597ceb_idx')],
            },
        ),
    ]
