# Generated by Django 6.0 on 2026-04-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0016_incidencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvaliacaoPedido",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token_publico", models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ("link_ativo", models.BooleanField(default=True)),
                ("email_enviado", models.BooleanField(default=False)),
                ("email_enviado_em", models.DateTimeField(blank=True, null=True)),
                ("email_tentativas", models.PositiveSmallIntegerField(default=0)),
                ("respondido_em", models.DateTimeField(blank=True, null=True)),
                ("p1_entrega_no_prazo", models.CharField(blank=True, max_length=3, null=True)),
                ("p2_aviso_antes_chegada", models.CharField(blank=True, max_length=3, null=True)),
                ("p3_educacao_simpatia", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("p4_cuidado_encomenda", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("p5_equipa_identificada", models.CharField(blank=True, max_length=3, null=True)),
                ("p6_facilidade_processo", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("p7_veiculo_limpo", models.CharField(blank=True, max_length=3, null=True)),
                ("p8_esclareceu_duvidas", models.CharField(blank=True, max_length=3, null=True)),
                ("p9_satisfacao_geral", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("p10_recomendaria", models.CharField(blank=True, max_length=3, null=True)),
                ("comentario", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pedido",
                    models.OneToOneField(
                        db_column="pedido_id",
                        on_delete=models.deletion.CASCADE,
                        related_name="avaliacao",
                        to="pedidos.pedido",
                    ),
                ),
            ],
            options={
                "db_table": "avaliacao_pedido",
                "indexes": [
                    models.Index(fields=["email_enviado"], name="avaliacao_p_email_e_6966e3_idx"),
                    models.Index(fields=["link_ativo"], name="avaliacao_p_link_at_c63b12_idx"),
                    models.Index(fields=["respondido_em"], name="avaliacao_p_respond_472c0c_idx"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="tentativaentrega",
            options={
                "permissions": [
                    ("change_carro_tentativaentrega", "Pode alterar o campo Carro na conferência de volumes"),
                    ("send_sms_tentativaentrega", "Pode enviar SMS de notificação de entrega"),
                    ("view_relatorio_gerencial", "Pode acessar o Relatório Gerencial de Pedidos"),
                    ("view_relatorio_avaliacao", "Pode acessar o Relatório de Avaliações"),
                    ("send_email_avaliacao", "Pode enviar e-mails de avaliação"),
                ]
            },
        ),
    ]
