# Generated by Django 6.0 on 2026-04-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0017_avaliacaopedido_and_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaopedido",
            name="origem_geracao",
            field=models.CharField(
                choices=[("MANUAL_RELATORIO", "Manual via Relatório")],
                default="MANUAL_RELATORIO",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="avaliacaopedido",
            name="selecionado_para_envio",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="avaliacaopedido",
            index=models.Index(fields=["selecionado_para_envio"], name="avaliacao_p_selecio_039bba_idx"),
        ),
        migrations.AlterModelOptions(
            name="tentativaentrega",
            options={
                "permissions": [
                    ("change_carro_tentativaentrega", "Pode alterar o campo Carro na conferência de volumes"),
                    ("send_sms_tentativaentrega", "Pode enviar SMS de notificação de entrega"),
                    ("view_relatorio_gerencial", "Pode acessar o Relatório Gerencial de Pedidos"),
                    ("view_relatorio_avaliacao", "Pode acessar o Relatório de Avaliações"),
                    ("send_email_avaliacao", "Pode enviar e-mails de avaliação"),
                    ("generate_email_queue_avaliacao", "Pode gerar fila de e-mails de avaliação"),
                ]
            },
        ),
    ]
