# Generated by Django 6.0 on 2026-05-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_avaliacaopedido_fila_fields_and_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(choices=[('Acondicionamento/Embalagem', 'Acondicionamento/Embalagem'), ('Peso/Volume', 'Peso/Volume'), ('Data/Horário', 'Data/Horário'), ('Pedido incompleto', 'Pedido incompleto'), ('Outros', 'Outros'), ('Artigo Danificado', 'Artigo Danificado'), ('Artigo Extraviado', 'Artigo Extraviado')], max_length=50),
        ),
    ]
