# Generated by Django 6.0 on 2026-05-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0020_alter_tentativaentrega_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidencia',
            options={
                'permissions': [
                    ('view_relatorio_incidencia', 'Pode acessar o Relatório de Incidências'),
                ],
            },
        ),
    ]
