# Generated by Django 6.0 on 2026-06-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0021_incidencia_view_relatorio_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoCritico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Produto crítico',
                'verbose_name_plural': 'Produtos críticos',
                'db_table': 'produto_critico',
                'ordering': ['codigo'],
                'constraints': [models.UniqueConstraint(fields=('codigo',), name='unique_produto_critico_codigo')],
            },
        ),
    ]
