# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0022_produto_critico"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidencia",
            name="resolvido",
            field=models.BooleanField(default=False),
        ),
    ]
