# Generated by Django 6.0 on 2026-09-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0025_pedido_conferir_etiqueta_enovo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(blank=True, choices=[('created', 'Criado'), ('assigned', 'Atribuído'), ('pending', 'Em distribuição'), ('completed', 'Concluído'), ('EA', 'Entrada em armazém e está OK'), ('CA', 'Cliente ausente'), ('R', 'Entrega recusada'), ('DA', 'Difícil acesso (rua)'), ('EM', 'Erro de morada'), ('DVP', 'Entrega com danos visíveis'), ('DVR', 'Entrada em armazém: danos visíveis'), ('cancelled', 'Cancelado'), ('A', 'Pedido Cancelado'), ('CI', 'Entrega com artigos em falta'), ('AO', 'Incumprimento do dia de entrega'), ('PNR', 'Pedido não rececionado'), ('RCD', 'Recolha com danos visíveis (casa cliente)'), ('PIT', 'Pedido incompleto: responsabilidade da transportadora'), ('reschedule_client', 'Reagendamento Responsabilidade Cliente'), ('reschedule_logisticOperator', 'Reagendamento Responsabilidade Transportador'), ('orders_vonzu', 'Entrada em Vonzu'), ('(orders_vonzu)', 'CONTACTO CONFIRMADO'), ('(orders_vonzu))', 'PENDENTE CONTACTO'), ('ExtraviadoOperador', 'Extraviado no Operador'), ('danos_visiveis_embalagem', 'Receção Transportadora: danos visíveis (embalagem)'), ('3799', 'Reagendado Zona Sem entregas dia Planeado'), ('recusa_parcial', 'Recusa parcial (artigos danificados)'), ('conferencia_condicionada', 'Conferência condicionada'), ('reactivar', 'Reactivar (Reagendamento responsabilidade Leroy Merlin)'), ('Reagendamento_Leroy_Merlin', 'Reagendamento responsabilidade Leroy Merlin'), ('returned_to_sender', 'Devolvido ao Cliente'), ('UNKNOWN', 'Estado desconhecido'), ('Incidência', 'Incidência'), ('Agendado', 'Agendado'), ('Aceite', 'Aceite'), ('Recolhido', 'Recolhido')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tentativaentrega',
            name='estado',
            field=models.CharField(blank=True, choices=[('created', 'Criado'), ('assigned', 'Atribuído'), ('pending', 'Em distribuição'), ('completed', 'Concluído'), ('EA', 'Entrada em armazém e está OK'), ('CA', 'Cliente ausente'), ('R', 'Entrega recusada'), ('DA', 'Difícil acesso (rua)'), ('EM', 'Erro de morada'), ('DVP', 'Entrega com danos visíveis'), ('DVR', 'Entrada em armazém: danos visíveis'), ('cancelled', 'Cancelado'), ('A', 'Pedido Cancelado'), ('CI', 'Entrega com artigos em falta'), ('AO', 'Incumprimento do dia de entrega'), ('PNR', 'Pedido não rececionado'), ('RCD', 'Recolha com danos visíveis (casa cliente)'), ('PIT', 'Pedido incompleto: responsabilidade da transportadora'), ('reschedule_client', 'Reagendamento Responsabilidade Cliente'), ('reschedule_logisticOperator', 'Reagendamento Responsabilidade Transportador'), ('orders_vonzu', 'Entrada em Vonzu'), ('(orders_vonzu)', 'CONTACTO CONFIRMADO'), ('(orders_vonzu))', 'PENDENTE CONTACTO'), ('ExtraviadoOperador', 'Extraviado no Operador'), ('danos_visiveis_embalagem', 'Receção Transportadora: danos visíveis (embalagem)'), ('3799', 'Reagendado Zona Sem entregas dia Planeado'), ('recusa_parcial', 'Recusa parcial (artigos danificados)'), ('conferencia_condicionada', 'Conferência condicionada'), ('reactivar', 'Reactivar (Reagendamento responsabilidade Leroy Merlin)'), ('Reagendamento_Leroy_Merlin', 'Reagendamento responsabilidade Leroy Merlin'), ('returned_to_sender', 'Devolvido ao Cliente'), ('UNKNOWN', 'Estado desconhecido'), ('Incidência', 'Incidência'), ('Agendado', 'Agendado'), ('Aceite', 'Aceite'), ('Recolhido', 'Recolhido')], max_length=50, null=True),
        ),
    ]
