# Generated by Django 6.0

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0026_alter_pedido_tentativa_estado_choices"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tentativaentrega",
            options={
                "permissions": [
                    (
                        "change_carro_tentativaentrega",
                        "Pode alterar o campo Carro na conferência de volumes",
                    ),
                    (
                        "send_sms_tentativaentrega",
                        "Pode enviar SMS de notificação de entrega",
                    ),
                    (
                        "view_relatorio_gerencial",
                        "Pode acessar o Relatório Gerencial de Pedidos",
                    ),
                    (
                        "view_relatorio_fechamento",
                        "Pode acessar o Relatório de Fechamento (logística)",
                    ),
                    (
                        "view_relatorio_avaliacao",
                        "Pode acessar o Relatório de Avaliações",
                    ),
                    (
                        "send_email_avaliacao",
                        "Pode enviar e-mails de avaliação",
                    ),
                    (
                        "generate_email_queue_avaliacao",
                        "Pode gerar fila de e-mails de avaliação",
                    ),
                    (
                        "download_anexo_gmail_gerencial",
                        "Pode descarregar anexos Gmail no Relatório Gerencial",
                    ),
                ],
            },
        ),
    ]
