# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0027_tentativaentrega_download_gmail_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="motivo_incidencia",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="tentativaentrega",
            name="motivo_incidencia",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
