# Generated by Django 6.0 on 2026-01-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuarios_options_alter_usuarios_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='nome',
        ),
    ]
