# Generated by Django 6.0 on 2026-04-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0002_filial_paises'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='lat_deposito',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='filial',
            name='lng_deposito',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
