# Generated by Django 6.0 on 2026-04-23 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0003_add_lat_lng_deposito'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilialConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sms_padrao_1', models.TextField(blank=True, null=True)),
                ('sms_padrao_2', models.TextField(blank=True, null=True)),
                ('filial', models.OneToOneField(db_column='filial_id', on_delete=django.db.models.deletion.CASCADE, related_name='config', to='filial.filial')),
            ],
            options={
                'db_table': 'filial_config',
            },
        ),
    ]
