# Generated by Django 6.0 on 2026-04-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0004_filialconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='filial',
            name='sms_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
