# Generated by Django 6.0 on 2026-04-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0005_filial_numero_filial_sms_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='numero',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
