# Generated by Django 6.0 on 2026-04-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0006_alter_filial_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='filialconfig',
            name='gsheets_sheet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filialconfig',
            name='gsheets_spreadsheet_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
