# Generated by Django 6.0 on 2026-04-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filial", "0009_alter_filialconfig_sms_auto"),
    ]

    operations = [
        migrations.AddField(
            model_name="filialconfig",
            name="email_auto",
            field=models.TimeField(
                blank=True,
                help_text="Horário (Lisboa) para envio automático diário de e-mails de avaliação.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="filialconfig",
            name="email_nome_remetente",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="filialconfig",
            name="email_template_assunto",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="filialconfig",
            name="email_template_corpo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
