# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filial", "0011_filialconfig_gsheets_segunda_planilha"),
    ]

    operations = [
        migrations.AddField(
            model_name="filialconfig",
            name="gmail_usuario",
            field=models.EmailField(
                blank=True,
                help_text="Conta Google Workspace cuja inbox é pesquisada (domain-wide delegation).",
                max_length=254,
                null=True,
            ),
        ),
    ]
