# Generated by Django 6.0 on 2026-05-03 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('filial', '0010_filialconfig_email_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, default='', max_length=30)),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(db_column='filial_id', on_delete=django.db.models.deletion.PROTECT, related_name='contas_financeiras', to='filial.filial')),
            ],
            options={
                'db_table': 'conta_financeira',
                'ordering': ['filial_id', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AdministradoraCartao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('cnpj', models.CharField(blank=True, default='', max_length=18)),
                ('conta_custodia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administradoras_cartao', to='financeiro.contafinanceira')),
            ],
            options={
                'db_table': 'administradora_cartao',
            },
        ),
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('observacao', models.TextField(blank=True, default='')),
                ('contraparte_pagamento_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('contraparte_pagamento_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('filial', models.ForeignKey(db_column='filial_id', on_delete=django.db.models.deletion.PROTECT, related_name='faturamentos', to='filial.filial')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faturamento',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('aceita_parcelamento', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('administradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagamento', to='financeiro.administradoracartao')),
                ('conta_custodia_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagamento_padrao', to='financeiro.contafinanceira')),
            ],
            options={
                'db_table': 'forma_pagamento',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='FaturamentoFormaPagamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('faturamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas_forma_pagamento', to='financeiro.faturamento')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_faturamento', to='financeiro.formapagamento')),
            ],
            options={
                'db_table': 'faturamento_forma_pagamento',
                'ordering': ['faturamento_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=40, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('nivel', models.PositiveSmallIntegerField()),
                ('tipo_classificacao', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('neutro', 'Neutro')], default='receita', max_length=20)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhos', to='financeiro.planocontas')),
            ],
            options={
                'db_table': 'plano_contas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroFinanceiro',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('TRANSFERENCIA', 'Transferência')], max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('parcial', 'Parcial'), ('liquidado', 'Liquidado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_fat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_rest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacao', models.TextField(blank=True, default='')),
                ('contraparte_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('referencia_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('contraparte_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('filial', models.ForeignKey(db_column='filial_id', on_delete=django.db.models.deletion.PROTECT, related_name='registros_financeiros', to='filial.filial')),
                ('plano_contas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_financeiros', to='financeiro.planocontas')),
                ('referencia_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_financeiro',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FaturamentoRegistroFinanceiro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('valor_abatido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('faturamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_registro', to='financeiro.faturamento')),
                ('filial', models.ForeignKey(db_column='filial_id', on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_faturamento_registro', to='filial.filial')),
                ('registro_financeiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_faturamento', to='financeiro.registrofinanceiro')),
            ],
            options={
                'db_table': 'faturamento_registro_financeiro',
                'ordering': ['faturamento_id', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='faturamento',
            name='registros_financeiros',
            field=models.ManyToManyField(related_name='faturamentos_vinculados', through='financeiro.FaturamentoRegistroFinanceiro', to='financeiro.registrofinanceiro'),
        ),
        migrations.CreateModel(
            name='ParcelaFaturamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_liquidacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('LIQUIDADO', 'Liquidado'), ('REPASSADO', 'Repassado'), ('DEVOLVIDO', 'Devolvido'), ('SUBSTITUIDO', 'Substituído'), ('ANTECIPADO', 'Antecipado')], default='ABERTO', max_length=20)),
                ('registro_gerado_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('conta_custodia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_custodia', to='financeiro.contafinanceira')),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_destino', to='financeiro.contafinanceira')),
                ('faturamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.faturamento')),
                ('faturamento_forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.faturamentoformapagamento')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_faturamento', to='financeiro.formapagamento')),
                ('registro_gerado_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'parcela_faturamento',
                'ordering': ['faturamento_id', 'id'],
                'indexes': [models.Index(fields=['faturamento', 'status'], name='parcela_fat_faturam_c71e44_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='registrofinanceiro',
            index=models.Index(fields=['filial', '-created_at'], name='registro_fi_filial__bb79ea_idx'),
        ),
        migrations.AddIndex(
            model_name='registrofinanceiro',
            index=models.Index(fields=['contraparte_content_type', 'contraparte_object_id'], name='registro_fi_contrap_920aed_idx'),
        ),
        migrations.AddIndex(
            model_name='registrofinanceiro',
            index=models.Index(fields=['referencia_content_type', 'referencia_object_id'], name='registro_fi_referen_501ff1_idx'),
        ),
        migrations.AddConstraint(
            model_name='faturamentoregistrofinanceiro',
            constraint=models.UniqueConstraint(fields=('faturamento', 'registro_financeiro'), name='unique_faturamento_registro_financeiro'),
        ),
        migrations.AddConstraint(
            model_name='faturamentoregistrofinanceiro',
            constraint=models.UniqueConstraint(fields=('faturamento', 'ordem'), name='unique_faturamento_ordem_abatimento'),
        ),
        migrations.AddIndex(
            model_name='faturamento',
            index=models.Index(fields=['filial', '-created_at'], name='faturamento_filial__96d4df_idx'),
        ),
    ]
