# Generated by Django 6.0 on 2026-05-08 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_plano_contas_arvore_completa'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofinanceiro',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='registrofinanceiro',
            name='data_vencimento',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
