# Generated by Django 6.0 on 2026-05-08 21:18

from django.db import migrations, models


def forwards_marcar_manual_legado(apps, schema_editor):
    RegistroFinanceiro = apps.get_model("financeiro", "RegistroFinanceiro")
    RegistroFinanceiro.objects.all().update(origem="manual")


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_registrofinanceiro_data_emissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofinanceiro',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('dominio', 'Sistema / Domínio')], db_index=True, default='dominio', max_length=20),
        ),
        migrations.RunPython(forwards_marcar_manual_legado, migrations.RunPython.noop),
    ]
