# Generated by Django 6.0

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0005_registrofinanceiro_origem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrofinanceiro",
            name="origem",
        ),
    ]
