"""
Django settings for sac_base project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import json
import dj_database_url
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default

    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=None):
    value = os.environ.get(name)
    if value is None:
        return list(default or [])

    return [item.strip() for item in value.split(",") if item.strip()]


URL_BD = os.environ.get('BANCO_DE_DADOS') or os.environ.get('DATABASE_URL')
SETTINGS_MODULE = os.environ.get('DJANGO_SETTINGS_MODULE', '')
USANDO_SETTINGS_TESTE_LOCAL = SETTINGS_MODULE == 'sac_base.settings_test'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEFAULT_DEV_SECRET_KEY = 'django-dev-sac-base-insecure-key'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', DEFAULT_DEV_SECRET_KEY)

_prod_like = not USANDO_SETTINGS_TESTE_LOCAL and SECRET_KEY != DEFAULT_DEV_SECRET_KEY
DEBUG = env_bool('DJANGO_DEBUG', default=not _prod_like)

ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    default=['127.0.0.1', 'localhost'] if DEBUG else [],
)

CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS', default=[])

SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', default=not DEBUG)
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', default=False)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if env_bool('DJANGO_USE_X_FORWARDED_PROTO', default=False) else None
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', 0 if DEBUG else 31536000))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG)
X_FRAME_OPTIONS = 'DENY'

AUTH_COOKIE_HTTPONLY = True
AUTH_COOKIE_SAMESITE = os.environ.get('DJANGO_AUTH_COOKIE_SAMESITE', 'Lax')
AUTH_COOKIE_SECURE = env_bool('DJANGO_AUTH_COOKIE_SECURE', default=not DEBUG)
ACTIVE_FILIAL_COOKIE_HTTPONLY = True
ACTIVE_FILIAL_COOKIE_SAMESITE = os.environ.get('DJANGO_ACTIVE_FILIAL_COOKIE_SAMESITE', AUTH_COOKIE_SAMESITE)
ACTIVE_FILIAL_COOKIE_SECURE = env_bool('DJANGO_ACTIVE_FILIAL_COOKIE_SECURE', default=AUTH_COOKIE_SECURE)

if not DEBUG and not USANDO_SETTINGS_TESTE_LOCAL and SECRET_KEY == DEFAULT_DEV_SECRET_KEY:
    raise RuntimeError('Defina DJANGO_SECRET_KEY para executar com DEBUG desabilitado')

if not DEBUG and not USANDO_SETTINGS_TESTE_LOCAL and not ALLOWED_HOSTS:
    raise RuntimeError('Defina DJANGO_ALLOWED_HOSTS para executar com DEBUG desabilitado')


# Application definition

INSTALLED_APPS = [
    'daphne',  # Deve ser o primeiro para sobrescrever o runserver com suporte a ASGI/WebSocket
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',  # WebSocket via Django Channels
    'rest_framework', # Necessário para o app de usuário/autenticação
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # JWT blacklist para invalidar tokens no logout
    'pages.cad_cliente',
    'pages.cad_grupo_cli',
    'pages.usuario',
    'pages.home',
    'pages.core',
    'pages.permissao',
    'pages.auditoria',
    'pages.filial',
    'pages.zona_entrega',
    'pages.motorista',
    'pages.pedidos',
    'pages.financeiro',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'sac_base.csp_middleware.CSPMiddleware',  # Content-Security-Policy
    'sac_base.csp_middleware.CSPMiddleware',  # Content-Security-Policy
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'pages.usuario.middleware.JWTAuthMiddleware', # Necessário para o app de usuário/autenticação
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
REST_FRAMEWORK = {# Necessário para o app de usuário/autenticação
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {# Necessário para o app de usuário/autenticação
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

ROOT_URLCONF = 'sac_base.urls'
ASGI_APPLICATION = 'sac_base.asgi.application'

# Channel Layers
# Em desenvolvimento usa InMemoryChannelLayer (processo único).
# Em produção multi-processo defina REDIS_URL e instale channels-redis.
_REDIS_URL = os.environ.get('REDIS_URL')
if _REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [_REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sac_base.context_processors.sisvar_global', # Context processor customizado para variável global sisVar
            ],
        },
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'pages.usuario.middleware': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

WSGI_APPLICATION = 'sac_base.wsgi.application'

AUTH_USER_MODEL = "usuario.Usuarios" # Necessário para o app de usuário/autenticação


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
if URL_BD:
    DATABASES = {
        'default': dj_database_url.config(
            default=URL_BD,
            conn_max_age=60,
            ssl_require=env_bool('DJANGO_DB_SSL_REQUIRE', default=not DEBUG),
        )
    }
elif USANDO_SETTINGS_TESTE_LOCAL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / '.django_test.sqlite3',
        }
    }
else:
    raise RuntimeError('Variável de ambiente BANCO_DE_DADOS não definida')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# E-mail (SMTP)
_email_auto_raw = os.environ.get("EMAIL_AUTO")
_email_auto_cfg = {}
if _email_auto_raw:
    try:
        _email_auto_cfg = json.loads(_email_auto_raw)
    except json.JSONDecodeError as exc:
        raise RuntimeError("EMAIL_AUTO inválida: JSON malformado.") from exc


def _email_cfg(name: str, default: str = ""):
    return str(_email_auto_cfg.get(name) or os.environ.get(name) or default)


EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = _email_cfg("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(_email_cfg("EMAIL_PORT", "587"))
EMAIL_USE_TLS = str(_email_cfg("EMAIL_USE_TLS", "true")).strip().lower() in {"1", "true", "yes", "on"}
EMAIL_USE_SSL = str(_email_cfg("EMAIL_USE_SSL", "false")).strip().lower() in {"1", "true", "yes", "on"}
EMAIL_HOST_USER = _email_cfg("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = _email_cfg("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = _email_cfg("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@sacbase.local")
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', 20))
EMAIL_SUBJECT_PREFIX = os.environ.get('EMAIL_SUBJECT_PREFIX', '')
APP_BASE_URL = _email_cfg("APP_BASE_URL", "http://127.0.0.1:8000")
AVALIACAO_TOKEN_SECRET = _email_cfg("AVALIACAO_TOKEN_SECRET", SECRET_KEY)