# Generated by Django 6.0 on 2026-04-12 17:44

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0002_filial_paises'),
        ('motorista', '0002_motorista_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='motorista',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='motorista',
            name='unique_motorista_codigo_ativo_por_filial',
        ),
        migrations.AlterField(
            model_name='motorista',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='motorista',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('codigo', ''), _negated=True), ('codigo__isnull', False)), fields=('filial', 'codigo'), name='unique_motorista_codigo_ativo_por_filial'),
        ),
    ]
