# Generated by Django 6.0 on 2026-05-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorista', '0003_alter_motorista_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='categoria',
            field=models.CharField(choices=[('LIGEIRO', 'Ligeiro'), ('PESADO', 'Pesado')], default='LIGEIRO', max_length=10),
        ),
    ]
