# Generated by Django 6.0 on 2026-05-11 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0010_filialconfig_email_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLogistica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pedidos_pesado', models.PositiveSmallIntegerField(default=0)),
                ('pesado_reservado', models.PositiveSmallIntegerField(default=0)),
                ('valor_unitario_pesado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pedidos_ligeiro', models.PositiveSmallIntegerField(default=0)),
                ('ligeiro_reservado', models.PositiveSmallIntegerField(default=0)),
                ('valor_unitario_ligeiro', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_excedente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('filial', models.OneToOneField(db_column='filial_id', on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_logistica', to='filial.filial')),
            ],
            options={
                'verbose_name': 'Configuração de Logística',
                'verbose_name_plural': 'Configurações de Logística',
                'db_table': 'configuracao_logistica',
            },
        ),
        migrations.CreateModel(
            name='DataExcecaoConfigLogistica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('pesado_reservado', models.PositiveSmallIntegerField(default=0)),
                ('ligeiro_reservado', models.PositiveSmallIntegerField(default=0)),
                ('configuracao', models.ForeignKey(db_column='configuracao_id', on_delete=django.db.models.deletion.CASCADE, related_name='datas_excecao', to='logistica_config.configuracaologistica')),
            ],
            options={
                'verbose_name': 'Data de exceção (logística)',
                'verbose_name_plural': 'Datas de exceção (logística)',
                'db_table': 'data_excecao_config_logistica',
                'indexes': [models.Index(fields=['configuracao', 'data'], name='data_exceca_configu_dd1d30_idx')],
                'constraints': [models.UniqueConstraint(fields=('configuracao', 'data'), name='unique_excecao_config_data')],
            },
        ),
    ]
