# Generated by Django 6.0 on 2026-06-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistica_config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodoExcecaoConfigLogistica",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("pesado_reservado", models.PositiveSmallIntegerField(default=0)),
                ("ligeiro_reservado", models.PositiveSmallIntegerField(default=0)),
                (
                    "configuracao",
                    models.ForeignKey(
                        db_column="configuracao_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodos_excecao",
                        to="logistica_config.configuracaologistica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Período de exceção (logística)",
                "verbose_name_plural": "Períodos de exceção (logística)",
                "db_table": "periodo_excecao_config_logistica",
                "indexes": [
                    models.Index(
                        fields=["configuracao", "data_inicio", "data_fim"],
                        name="periodo_exc_cfg_ini_fim_idx",
                    ),
                ],
            },
        ),
    ]
