# Generated by Django 6.0 on 2026-03-27 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_cliente', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='uf',
        ),
        migrations.AddField(
            model_name='cliente',
            name='regiao',
            field=models.ForeignKey(blank=True, db_column='regiao_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.regiao'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.ForeignKey(blank=True, db_column='cidade_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=models.ForeignKey(db_column='pais_id', on_delete=django.db.models.deletion.PROTECT, to='core.pais'),
        ),
    ]
