# Generated by Django 6.0 on 2026-03-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_cliente', '0002_remove_cliente_uf_cliente_regiao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observacao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
