# Generated by Django 6.0 on 2026-03-27 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('sigla', models.CharField(max_length=3, unique=True)),
                ('codigo_tel', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'verbose_name': 'País',
                'db_table': 'global_pais',
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_uf', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=2)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regioes', to='core.pais')),
            ],
            options={
                'verbose_name': 'Estado/Região',
                'db_table': 'global_regiao',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cid', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='core.regiao')),
            ],
            options={
                'verbose_name': 'Cidade',
                'db_table': 'global_cidade',
                'ordering': ['nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='regiao',
            constraint=models.UniqueConstraint(fields=('id_uf', 'pais'), name='unique_regiao_por_pais', violation_error_message='Esta região já está cadastrada neste país.'),
        ),
        migrations.AddConstraint(
            model_name='cidade',
            constraint=models.UniqueConstraint(fields=('id_cid', 'regiao'), name='unique_cidade_por_regiao', violation_error_message='Esta cidade já está cadastrada neste estado/distrito.'),
        ),
    ]
