# Generated by Django 6.0 on 2026-01-01 18:54

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCli',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'grupo_cli',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('descricao'), name='unique_descricao_upper')],
            },
        ),
    ]
