# Generated by Django 6.0 on 2026-05-18 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('filial', '0010_filialconfig_email_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaManual',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('categoria', models.CharField(choices=[('financeiro', 'Financeiro'), ('operacional', 'Operacional'), ('lembrete', 'Lembrete')], default='lembrete', max_length=40)),
                ('modo_evento', models.CharField(choices=[('aviso', 'Aviso simples'), ('aviso_confirmavel', 'Aviso com confirmação'), ('materializavel', 'Lançamento vinculado')], default='aviso', max_length=30)),
                ('tipo_materializacao', models.CharField(blank=True, max_length=80, null=True)),
                ('payload_template', models.JSONField(blank=True, default=dict)),
                ('payload_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('data_ancora', models.DateField()),
                ('recorrencia', models.CharField(choices=[('nenhuma', 'Nenhuma (evento único)'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=20)),
                ('intervalo', models.PositiveSmallIntegerField(default=1)),
                ('dia_semana', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dia_mes_fixo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('antecipar_fim_semana', models.BooleanField(default=False)),
                ('data_fim_serie', models.DateField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('filial', models.ForeignKey(db_column='filial_id', on_delete=django.db.models.deletion.PROTECT, related_name='agendas_manuais', to='filial.filial')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agenda_manual',
                'ordering': ['filial_id', 'titulo', 'id'],
                'permissions': [('view_relatorio_previsibilidade', 'Ver relatório de previsibilidade'), ('confirmar_ocorrencia_agendamanual', 'Confirmar ocorrência de agenda'), ('materializar_agendamanual', 'Materializar ocorrência de agenda')],
            },
        ),
        migrations.CreateModel(
            name='AgendaMaterializacao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_ocorrencia', models.DateField()),
                ('tipo_vinculo', models.CharField(max_length=40)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('agenda_manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materializacoes', to='agenda.agendamanual')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agenda_materializacao',
                'ordering': ['-data_ocorrencia', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='agendamanual',
            index=models.Index(fields=['filial', 'ativa'], name='agenda_manu_filial__4c4bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamanual',
            index=models.Index(fields=['filial', 'data_ancora'], name='agenda_manu_filial__a025ea_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamanual',
            index=models.Index(fields=['filial', 'tipo_materializacao'], name='agenda_manu_filial__7eb557_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamaterializacao',
            index=models.Index(fields=['agenda_manual', 'data_ocorrencia'], name='agenda_mate_agenda__a6fd15_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendamaterializacao',
            constraint=models.UniqueConstraint(fields=('agenda_manual', 'data_ocorrencia'), name='uq_agenda_materializacao_manual_data'),
        ),
    ]
